<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="uiens-MBP" ignored="0" name="Group 4" tests="10" failures="3" timestamp="2022-04-02T11:22:11 ICT" time="44.406" errors="0">
  <testcase name="importantMethod" time="0.07" classname="test.global.FooterTestCopy">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at test.global.FooterTestCopy.importantMethod(FooterTestCopy.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- importantMethod -->
  <testcase name="anotherTestMethodCopy" time="0.001" classname="test.global.FooterTestCopy">
    <skipped/>
  </testcase> <!-- anotherTestMethodCopy -->
  <testcase name="testCategoryPageHeader" time="11.857" classname="test.global.HeaderTest"/>
  <testcase name="testHomepageHeader" time="9.014" classname="test.global.HeaderTest"/>
  <testcase name="testHomepageHeader_" time="9.122" classname="test.global.HeaderTest"/>
  <testcase name="testRegisterPageHeader" time="5.36" classname="test.global.HeaderTest"/>
  <testcase name="testRegisterPageHeader_" time="8.818" classname="test.global.HeaderTest"/>
  <testcase name="testHardAssertion" time="0.019" classname="test.global.TestNGAssertionTypes">
    <failure type="java.lang.AssertionError" message="[ERR] Now 1 == 2 expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: [ERR] Now 1 == 2 expected [2] but found [1]
at test.global.TestNGAssertionTypes.testHardAssertion(TestNGAssertionTypes.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testHardAssertion -->
  <testcase name="testSoftAssertion" time="0.004" classname="test.global.TestNGAssertionTypes">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[ERR] Now 1 == 2 expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[ERR] Now 1 == 2 expected [2] but found [1]
at test.global.TestNGAssertionTypes.testSoftAssertion(TestNGAssertionTypes.java:24)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testSoftAssertion -->
  <testcase name="testHomepageFooterCopy" time="0.0" classname="test.global.FooterTestCopy"/>
</testsuite> <!-- Group 4 -->
